CC      = gcc
CCFLAGS = -Wall -Werror -std=c17
LDLIBS  =
dealer: card.o hand.o deck.o dealer.o
	$(CC) -o $@ $^ $(LDLIBS)
card.o: card.c card.h
	$(CC) -c card.c $(CCFLAGS)
hand.o: hand.c hand.h card.h
	$(CC) -c hand.c $(CCFLAGS)
deck.o: deck.c deck.h card.h
	$(CC) -c deck.c $(CCFLAGS)
dealer.o: dealer.c deck.h hand.h card.h
	$(CC) -c dealer.c $(CCFLAGS)

.PHONY: clean
clean:
	rm -f *.o
	rm dealer

.PHONY: run
run:
	./dealer
